name: CI

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.x'

    - run: flutter pub get
    - run: flutter build windows --release

    - uses: actions/upload-artifact@v1
      with:
        name: release-windows
        path: build\windows\runner\Release\